# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T15:22:41+00:00



import argparse
import json
import os
from typing import *
from typing import Optional, Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import APIKeyHeader, BaseSecurity

from models import (
    DpcerCertificatePostRequest,
    DpcerCertificatePostResponse,
    DpcerCertificatePostResponse1,
    DpcerCertificatePostResponse2,
    DpcerCertificatePostResponse3,
    DpcerCertificatePostResponse4,
    DpcerCertificatePostResponse5,
    DpcerCertificatePostResponse6,
)

app = MCPProxy(
    description='Department of Sainik Welfare Society (www.sainikwelfare.puducherry.gov.in) is issuing digital &#34;Dependency Certificate&#34; . These certificates are being made available through DigiLocker. These Certificates can be pulled by citizens into their DigiLocker accounts.',
    termsOfService='https://apisetu.gov.in/terms.php',
    title='Department of Sainik Welfare, Puducherry',
    version='3.0.0',
    servers=[{'url': 'https://apisetu.gov.in/sainikwelfarepud/v3'}],
)


@app.post(
    '/dpcer/certificate',
    description=""" API to verify Dependency Certificate. """,
    tags=['dependency_certification'],
    security=[
        APIKeyHeader(name="X-APISETU-APIKEY"),
        APIKeyHeader(name="X-APISETU-CLIENTID"),
    ],
)
def dpcer(body: DpcerCertificatePostRequest = None):
    """
    Dependency Certificate
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
